# EXAMPLE Gemfile for a spree application, your Gemfile will be different
source 'http://rubygems.org'

# Generic gem dependencies first
gem 'rails', '3.0.5'
gem 'aws-s3', :require => 'aws/s3'
gem 'dynamic_form'
gem 'heroku'
gem 'memcache-client'

# Followed by spree itself first, all spree-specific extensions second
gem 'spree', '~> 0.50.0'
gem 'spree_static_content'
gem 'spree_editor', :git => "git://github.com/romul/spree_editor.git"
gem 'spree_product_assembly', :git => 'git://github.com/spree/spree-product-assembly.git'

# Dev/Test gems
group :development, :test do
gem 'sqlite3'
gem 'webrat'
gem 'cucumber-rails'
gem 'rspec-rails'
end

# EOF